#pragma once
#include <optional>
#include <cusp/coo_matrix.h>
#include <cusp/csr_matrix.h>
#include <npy.hpp>
#include "MySimpleNDArray.h"
#include "../utils.h"
#include "../MyHyb/MyHyb.h"
#include "../hetero_edgesoftmax.h"
#include "DGLHackUtils.h"
#include "FusedGAT.h"
#include "FusedGATBackward.h"

#include "RGCNLayers.h"
#include "RGCNLayersBackward.h"
#include "RGCNLayer1MyHYB.h"
#include "RGCNLayer1BackwardMyHYB.h"
#include "HGTExperimental.h"
#include "HGTBackPropGradientSmAFusion.h"
#include "DGLHackKernelInit.h"
