name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # explicit include-based build matrix, of known valid options
      matrix:
        include:
          # 20.04 supports CUDA 11.0+
          - os: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        token: ${{ secrets.READONLY_PAK }}
    - uses: Jimver/cuda-toolkit@v0.2.4
      id: cuda-toolkit
      with:
        cuda: '11.2.2'
    # - run: echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
    # - run: echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
    - run: nvcc -V
    - name: install glog
      run: sudo apt-get install -y libgflags-dev libgoogle-glog-dev
    # there might be -DCMAKE_PREFIX_PATH=`python -c 'import torch;print(torch.utils.cmake_prefix_path)'` needed when doing cmake configure for building purpose. We ignored it here in order not to install pytorch in this simple ci test.
    - name: make
      run: |
        mkdir build
        cd build
        cmake .. -DCUDA_ARCHS="75;80" -DBUILD_TEST=ON -DBUILD_BENCHMARK=ON -DBUILD_GENERATED=ON -DBUILD_TORCH_API=OFF
        make
        make DESTDIR=./install install
